### ISSUE TITLE
admin login problem 

### ISSUE THREAD

**Issue by krazaa** [muvatech/Laravel-5.4-Multiple-Authentication-System#1]
hi when i try login i get this error View [.] not found. how to fix plz.

**Comment by henrymbuguak** [comment]
Hi Krazaa,

![tinker](https://user-images.githubusercontent.com/14896749/30734724-11ecdece-9f85-11e7-9380-22eecd1f7e04.png)

You need to add, admin to the database before you try to login. In the above image, there is an example of how to use tinker to add user to the database. After adding admin to database: navigate to this url and try to login. http://localhost:8000/admin/login/ If you are unable to login send me the process you are doing from cloning the project to configuring database connection and migration.
